-- Add missing columns to resources table
ALTER TABLE resources ADD COLUMN IF NOT EXISTS title VARCHAR(200);
ALTER TABLE resources ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS resource_type resource_type;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS file_url VARCHAR(500);
ALTER TABLE resources ADD COLUMN IF NOT EXISTS file_size INTEGER;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS mime_type VARCHAR(100);
ALTER TABLE resources ADD COLUMN IF NOT EXISTS access_level resource_access_level;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS required_roles JSONB;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS categories JSONB;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS tags JSONB;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS uploaded_by INTEGER REFERENCES users(id);
ALTER TABLE resources ADD COLUMN IF NOT EXISTS uploaded_at TIMESTAMP DEFAULT NOW();
ALTER TABLE resources ADD COLUMN IF NOT EXISTS last_updated TIMESTAMP DEFAULT NOW();
ALTER TABLE resources ADD COLUMN IF NOT EXISTS download_count INTEGER DEFAULT 0;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS average_rating DECIMAL(3, 2);