'use server';

import { db } from '@/lib/db/drizzle';
import {
  invitationCodes,
  invitationCodeUsages,
  membershipPurchases,
  activityLogs,
  type NewInvitationCode,
  type NewInvitationCodeUsage,
  type InvitationCode,
  ActivityType,
} from '@/lib/db/schema';
import { eq, and, gt, lt, sql, or } from 'drizzle-orm';
import { nanoid } from 'nanoid';

/**
 * Generates a unique invitation code with specified format.
 * Format: SHP-XXXX-XXXX-XXXX (16 chars total, easy to read)
 */
function generateCodeString(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // Removed confusing chars: I,O,0,1
  let code = 'SHP-';
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 4; j++) {
      code += chars[Math.floor(Math.random() * chars.length)];
    }
    if (i < 2) code += '-';
  }
  return code;
}

export interface CreateInvitationCodeParams {
  codeType: 'payment' | 'mentor_approved' | 'mentee_approved' | 'admin_generated';
  maxUses?: number;
  expiresAt?: Date;
  purchaseId?: number;
  generatedBy?: number;
  generatedFor?: string;
  notes?: string;
  metadata?: Record<string, unknown>;
  // New fields for role-based registration
  targetRole?: 'mentor' | 'mentee' | 'admin';
  linkedFormId?: number;
  linkedFormType?: 'mentor' | 'mentee';
}

/**
 * Creates a new invitation code.
 * Used after successful payment or admin approval.
 */
export async function createInvitationCode(params: CreateInvitationCodeParams): Promise<InvitationCode> {
  const {
    codeType,
    maxUses = 1,
    expiresAt,
    purchaseId,
    generatedBy,
    generatedFor,
    notes,
    metadata,
    targetRole,
    linkedFormId,
    linkedFormType,
  } = params;

  // Generate unique code, retry if collision
  let code: string;
  let attempts = 0;
  const maxAttempts = 10;

  while (attempts < maxAttempts) {
    code = generateCodeString();
    const existing = await db
      .select({ id: invitationCodes.id })
      .from(invitationCodes)
      .where(eq(invitationCodes.code, code))
      .limit(1);

    if (existing.length === 0) break;
    attempts++;
  }

  if (attempts >= maxAttempts) {
    throw new Error('Failed to generate unique invitation code');
  }

  // Set default expiration (30 days for payment codes, 7 days for others)
  const defaultExpiry = codeType === 'payment'
    ? new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
    : new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);

  const newCode: NewInvitationCode = {
    code: code!,
    codeType,
    status: 'active',
    maxUses,
    currentUses: 0,
    expiresAt: expiresAt || defaultExpiry,
    purchaseId,
    generatedBy,
    generatedFor,
    notes,
    metadata,
    targetRole,
    linkedFormId,
    linkedFormType,
  };

  const [created] = await db.insert(invitationCodes).values(newCode).returning();

  // Log activity if generated by a user
  if (generatedBy) {
    await db.insert(activityLogs).values({
      userId: generatedBy,
      action: ActivityType.GENERATE_INVITATION_CODE,
      entityType: 'invitation_code',
      entityId: created.id,
      metadata: {
        codeType,
        generatedFor,
        expiresAt: created.expiresAt?.toISOString(),
      },
    });
  }

  return created;
}

export interface ValidateCodeResult {
  valid: boolean;
  code?: InvitationCode;
  error?: string;
}

/**
 * Validates an invitation code without using it.
 * Checks: existence, status, expiration, usage count.
 */
export async function validateInvitationCode(codeString: string): Promise<ValidateCodeResult> {
  // Normalize code (uppercase, trim)
  const normalizedCode = codeString.toUpperCase().trim();

  const [code] = await db
    .select()
    .from(invitationCodes)
    .where(eq(invitationCodes.code, normalizedCode))
    .limit(1);

  if (!code) {
    return { valid: false, error: 'Invalid invitation code' };
  }

  if (code.status === 'revoked') {
    return { valid: false, error: 'This invitation code has been revoked' };
  }

  if (code.status === 'used') {
    return { valid: false, error: 'This invitation code has already been used' };
  }

  if (code.status === 'expired') {
    return { valid: false, error: 'This invitation code has expired' };
  }

  if (code.expiresAt && new Date(code.expiresAt) < new Date()) {
    // Auto-update status to expired
    await db
      .update(invitationCodes)
      .set({ status: 'expired', updatedAt: new Date() })
      .where(eq(invitationCodes.id, code.id));
    return { valid: false, error: 'This invitation code has expired' };
  }

  if (code.currentUses >= (code.maxUses || 1)) {
    // Auto-update status to used
    await db
      .update(invitationCodes)
      .set({ status: 'used', updatedAt: new Date() })
      .where(eq(invitationCodes.id, code.id));
    return { valid: false, error: 'This invitation code has reached its usage limit' };
  }

  return { valid: true, code };
}

export interface UseCodeResult {
  success: boolean;
  code?: InvitationCode;
  error?: string;
}

/**
 * Uses an invitation code for user registration.
 * Records usage and updates code status.
 */
export async function useInvitationCode(
  codeString: string,
  userId: number,
  ipAddress?: string,
  userAgent?: string
): Promise<UseCodeResult> {
  // First validate the code
  const validation = await validateInvitationCode(codeString);
  if (!validation.valid || !validation.code) {
    return { success: false, error: validation.error };
  }

  const code = validation.code;

  // Check if user already used this code
  const existingUsage = await db
    .select()
    .from(invitationCodeUsages)
    .where(
      and(
        eq(invitationCodeUsages.codeId, code.id),
        eq(invitationCodeUsages.usedByUserId, userId)
      )
    )
    .limit(1);

  if (existingUsage.length > 0) {
    return { success: false, error: 'You have already used this invitation code' };
  }

  // Record usage
  const usage: NewInvitationCodeUsage = {
    codeId: code.id,
    usedByUserId: userId,
    ipAddress,
    userAgent,
  };

  await db.insert(invitationCodeUsages).values(usage);

  // Update code usage count and status
  const newUses = code.currentUses + 1;
  const newStatus = newUses >= (code.maxUses || 1) ? 'used' : 'active';

  await db
    .update(invitationCodes)
    .set({
      currentUses: newUses,
      status: newStatus,
      updatedAt: new Date(),
    })
    .where(eq(invitationCodes.id, code.id));

  // Log activity
  await db.insert(activityLogs).values({
    userId,
    action: ActivityType.USE_INVITATION_CODE,
    entityType: 'invitation_code',
    entityId: code.id,
    ipAddress,
    metadata: {
      codeType: code.codeType,
    },
  });

  // Return updated code
  const [updatedCode] = await db
    .select()
    .from(invitationCodes)
    .where(eq(invitationCodes.id, code.id))
    .limit(1);

  return { success: true, code: updatedCode };
}

/**
 * Revokes an invitation code (admin action).
 */
export async function revokeInvitationCode(
  codeId: number,
  revokedBy: number,
  reason?: string
): Promise<boolean> {
  const [code] = await db
    .select()
    .from(invitationCodes)
    .where(eq(invitationCodes.id, codeId))
    .limit(1);

  if (!code) {
    return false;
  }

  await db
    .update(invitationCodes)
    .set({
      status: 'revoked',
      notes: reason ? `${code.notes || ''}\nRevoked: ${reason}` : code.notes,
      updatedAt: new Date(),
    })
    .where(eq(invitationCodes.id, codeId));

  // Log activity
  await db.insert(activityLogs).values({
    userId: revokedBy,
    action: 'REVOKE_INVITATION_CODE' as any,
    entityType: 'invitation_code',
    entityId: codeId,
    metadata: { reason },
  });

  return true;
}

/**
 * Gets invitation codes with pagination and filtering.
 */
export async function getInvitationCodes(options: {
  status?: 'active' | 'used' | 'expired' | 'revoked';
  codeType?: 'payment' | 'mentor_approved' | 'mentee_approved' | 'admin_generated';
  generatedBy?: number;
  limit?: number;
  offset?: number;
}) {
  const { status, codeType, generatedBy, limit = 50, offset = 0 } = options;

  const conditions = [];

  if (status) {
    conditions.push(eq(invitationCodes.status, status));
  }
  if (codeType) {
    conditions.push(eq(invitationCodes.codeType, codeType));
  }
  if (generatedBy) {
    conditions.push(eq(invitationCodes.generatedBy, generatedBy));
  }

  const query = db
    .select()
    .from(invitationCodes)
    .where(conditions.length > 0 ? and(...conditions) : undefined)
    .orderBy(sql`${invitationCodes.createdAt} DESC`)
    .limit(limit)
    .offset(offset);

  return query;
}

/**
 * Gets code usage history for a specific code.
 */
export async function getCodeUsageHistory(codeId: number) {
  return db
    .select()
    .from(invitationCodeUsages)
    .where(eq(invitationCodeUsages.codeId, codeId))
    .orderBy(sql`${invitationCodeUsages.usedAt} DESC`);
}

/**
 * Cleanup expired codes (scheduled job).
 */
export async function cleanupExpiredCodes(): Promise<number> {
  // First get count of codes to be updated
  const expiredCodes = await db
    .select({ id: invitationCodes.id })
    .from(invitationCodes)
    .where(
      and(
        eq(invitationCodes.status, 'active'),
        lt(invitationCodes.expiresAt, new Date())
      )
    );

  if (expiredCodes.length === 0) {
    return 0;
  }

  // Update the codes
  await db
    .update(invitationCodes)
    .set({ status: 'expired', updatedAt: new Date() })
    .where(
      and(
        eq(invitationCodes.status, 'active'),
        lt(invitationCodes.expiresAt, new Date())
      )
    );

  return expiredCodes.length;
}

/**
 * Creates invitation code after successful payment.
 * Links code to purchase record and mentee form.
 */
export async function createPaymentInvitationCode(
  purchaseId: number,
  recipientEmail: string,
  linkedFormId?: number
): Promise<InvitationCode> {
  // Get purchase details
  const [purchase] = await db
    .select()
    .from(membershipPurchases)
    .where(eq(membershipPurchases.id, purchaseId))
    .limit(1);

  if (!purchase) {
    throw new Error('Purchase not found');
  }

  return createInvitationCode({
    codeType: 'payment',
    maxUses: 1,
    purchaseId,
    generatedBy: purchase.userId || undefined,
    generatedFor: recipientEmail,
    notes: `Generated from membership purchase #${purchaseId}`,
    metadata: {
      membershipTier: purchase.membershipTier,
      amountPaid: purchase.amountPaid,
      stripePaymentIntentId: purchase.stripePaymentIntentId,
    },
    // Role-based registration fields
    targetRole: 'mentee',
    linkedFormId,
    linkedFormType: linkedFormId ? 'mentee' : undefined,
  });
}

/**
 * Creates invitation code after mentor application approval.
 * Links code to mentor form submission.
 */
export async function createMentorApprovalCode(
  mentorEmail: string,
  approvedBy: number,
  linkedFormId: number,
  notes?: string
): Promise<InvitationCode> {
  return createInvitationCode({
    codeType: 'mentor_approved',
    maxUses: 1,
    generatedBy: approvedBy,
    generatedFor: mentorEmail,
    notes: notes || 'Generated after mentor application approval',
    // Role-based registration fields
    targetRole: 'mentor',
    linkedFormId,
    linkedFormType: 'mentor',
  });
}

/**
 * Creates invitation code after mentee application approval.
 * Links code to mentee form submission.
 */
export async function createMenteeApprovalCode(
  menteeEmail: string,
  approvedBy: number,
  linkedFormId: number,
  notes?: string
): Promise<InvitationCode> {
  return createInvitationCode({
    codeType: 'mentee_approved',
    maxUses: 1,
    generatedBy: approvedBy,
    generatedFor: menteeEmail,
    notes: notes || 'Generated after mentee application approval',
    targetRole: 'mentee',
    linkedFormId,
    linkedFormType: 'mentee',
  });
}

/**
 * Creates admin-generated invitation code.
 * Can optionally specify a target role for the invitation.
 */
export async function createAdminCode(
  adminUserId: number,
  options: {
    maxUses?: number;
    expiresAt?: Date;
    recipientEmail?: string;
    notes?: string;
    targetRole?: 'mentor' | 'mentee' | 'admin';
  }
): Promise<InvitationCode> {
  return createInvitationCode({
    codeType: 'admin_generated',
    maxUses: options.maxUses || 1,
    expiresAt: options.expiresAt,
    generatedBy: adminUserId,
    generatedFor: options.recipientEmail,
    notes: options.notes || 'Admin-generated invitation code',
    targetRole: options.targetRole,
  });
}

/**
 * Gets statistics about invitation codes.
 */
export async function getInvitationCodeStats() {
  const stats = await db
    .select({
      status: invitationCodes.status,
      codeType: invitationCodes.codeType,
      count: sql<number>`count(*)::int`,
    })
    .from(invitationCodes)
    .groupBy(invitationCodes.status, invitationCodes.codeType);

  return stats;
}
